#!/bin/sh
# /etc/periodic/monthly/reissue

# shell script best practice
set -euo pipefail

# stop nginx before renewing to open port 80
/etc/init.d/nginx stop

# renew certs
letsencrypt certonly --renew-by-default \
        --domain seednode.co
        --authenticator webroot
        --webroot-path /etc/letsencrypt/webrootauth/
        --email jpsinkula@hotmail.com --agree-tos

# start nginx again
/etc/init.d/nginx start
