#!/bin/bash                                                                                                                                                  __
# a script to share your terminal with GoTTY; run the accompanying "join" script to connect to the created session
                                                                                                                                                   __
# check for existing tmux instances                                                                                                                          __
existing_sessions=$(tmux list-sessions | head -n1 | cut -d ":" -f 1 | grep run-gotty)                                                                        __
                                                                                                                                                             __
# if an instance doesn't exist, create one. Otherwise, attach to the existing one.                                                                           __
if [ -z "$existing_sessions" ]                                                                                                                               __
    then                                                                                                                                                     __
        tmux kill-session -t run-gotty                                                                                                                       __
        tmux new-session -d -s run-gotty                                                                                                                     __
        tmux send -t run-gotty "gotty --title-format 'Twitch Plays Sysadmin' tmux new -A -s gotty /bin/zsh" Enter                                            __
    else                                                                                                                                                     __
        tmux new-session -d -s run-gotty                                                                                                                     __
        tmux send -t run-gotty "gotty --title-format 'Twitch Plays Sysadmin' tmux new -A -s gotty /bin/zsh" Enter                                            __
fi                                                                                                                                                           __
                                                                                                                                                             __
# connect to the tmux session locally                                                                                                                        __
tmux new -A -s gotty
